  source("Prog/MultBlocClassement.R")
  source("Prog/MultBlocICL.R")
  source("Prog/MultBlocXemAlpha_kl.R")
  source("Prog/MultBlocRnd.R")
  source("Prog/MultBlocVBayes.R")
  source("Prog/MultBlocVisu.R")
  source("Prog/Init_Mult.R")
  source("Prog/PartRnd.R")
  source("Prog/BlocGibbsMult.R")
  source("Prog/MultBlocGibbs.R")
#  source("Prog/BinBlocGVB.R")
#  source("Prog/BinBlocVisuResum.R")
#  source("Prog/BinBlocInfo.R")
#  source("Prog/CARI.R")
