
 source("Prog/BinBlocClassement_LBM.R")
 source("Prog/BinBlocICL_LBM.R")
 source("Prog/BlocXemAlpha_kl_LBM.R")
 source("Prog/BinBlocRnd.R")
 source("Prog/BinBlocVBayes_LBM.R")
 source("Prog/BinBlocVisu_LBM.R")
 source("Prog/Init.R")
 source("Prog/Init_LBM.R")
 source("Prog/PartRnd.R")
 source("Prog/BlocGibbs_LBM.R")
 source("Prog/BinBlocGibbs_LBM.R")
# source("Prog/BinBlocGVB.R")
 source("Prog/BinBlocVisuResum.R")
# source("Prog/BinBlocInfo.R")
 source("Prog/CARI.R")

